#
# This source file is part of the ResearchKitOnFHIR open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test Swift Package
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: ResearchKitOnFHIR-Package.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: ResearchKitOnFHIR-Package
  buildandtestvisionos:
    name: Build and Test Swift Package visionOS
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: ResearchKitOnFHIR-Package-visionOS.xcresult
      resultBundle: ResearchKitOnFHIR-Package-visionOS.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: ResearchKitOnFHIR-Package
      destination: 'platform=visionOS Simulator,name=Apple Vision Pro'
  buildandtestuitests:
    name: Build and Test UI Tests
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: Example.xcresult
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Example'
      scheme: Example
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [buildandtest, buildandtestvisionos, buildandtestuitests]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: ResearchKitOnFHIR-Package.xcresult ResearchKitOnFHIR-Package-visionOS.xcresult Example.xcresult
