#
# This source file is part of the ResearchKitOnFHIR open source project
#
# SPDX-FileCopyrightText: 2022 CardinalKit and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    name: Build and test
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
    - name: Build and test
      run: xcodebuild test -scheme ResearchKitOnFHIR -sdk iphonesimulator -destination "name=iPhone 13 Pro" CODE_SIGNING_ALLOWED="NO" -enableCodeCoverage YES
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
