#
# This source file is part of the ResearchKitOnFHIR open source project
#
# SPDX-FileCopyrightText: 2022 CardinalKit and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docs:
    name: Generate Docs
    uses: CardinalKit/.github/.github/workflows/docs.yml@improveGitHubActions
    with:
      targetname: ResearchKitOnFHIR
