#
# This source file is part of the ResearchKitOnFHIR open source project
#
# SPDX-FileCopyrightText: 2022 CardinalKit and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Generate Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  macos:
    name: Generate Docs
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
    - name: Generate Documentation
      run: |
          xcodebuild docbuild \
            -scheme ResearchKitOnFHIR-Package \
            -destination "name=iPhone 14 Pro" \
            -derivedDataPath .build
    - name: Generate static hosting files
      run: |
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting .build/Build/Products/Debug-iphonesimulator/ResearchKitOnFHIR.doccarchive \
            --output-path ./docs \
            --hosting-base-path ResearchKitOnFHIR
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./docs
        force_orphan: true